spring:
  application:
    name: Project_5
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    active: development
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    enabled: true
    encoding: UTF-8

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
