spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
  database-platform: org.hibernate.dialect.Postgresql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    enabled: true
    encoding: UTF-8

debug: true
logging:
  level:
    root: debug
    org.springframework.web: debug
    org.apache.coyote.http11: debug